version: "3.8"
services:
  web:
    image: investigation-frontend-image:1-initial
    container_name: web-service
    restart: "no"
    ports:
      - 5000:80
    depends_on:
      - backend
  backend:
    image: investigation-backend-image:1-initial
    container_name: backend-service
    ports:
      - 8080:5000
    restart: "no"
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres
    container_name: postgresdb-service
    restart: "no"
    ports:
      - 5432:5432
    volumes:
      - /usr/vlad/docker-compose/mount/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pspostgres
      - POSTGRES_DB=app

